<?php
    namespace App\Providers;

    use App\Services\PostService;
    use Bearlovescode\Bluesky\Models\Service\Configuration as BlueskyConfiguration;
    use Bearlovescode\Bluesky\Services\RepoService;
    use Bearlovescode\Bluesky\Services\ServerService;
    use Illuminate\Support\ServiceProvider;

    class BlueskyServiceProvider extends ServiceProvider
    {
        public function register()
        {
            parent::register(); // TODO: Change the autogenerated stub

            $this->app->singleton(ServerService::class, function () {
                return new ServerService($this->getConfiguration());
            });

            $this->app->singleton(RepoService::class, function () {
                return new RepoService($this->getConfiguration());

            });
        }

        public function getConfiguration(): BlueskyConfiguration
        {
            return new BlueskyConfiguration([
                'baseUri' => 'https://bsky.social/xrpc'
            ]);
        }
    }
