<?php
    namespace App\Providers;

    use Illuminate\Support\ServiceProvider;

    class MastodonServiceProvider extends ServiceProvider
    {
        public function register()
        {
            parent::register(); // TODO: Change the autogenerated stub
        }
    }
